// This file will be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts
//
// For now, here are the basic types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      clinics_pending_review: {
        Row: {
          id: string
          hcp_number: string
          clinic_name: string
          address: string | null
          city: string | null
          state: string
          filing_date: string
          form_465_hash: string
          service_type: string | null
          contract_length: number | null
          bandwidth: string | null
          priority_score: number | null
          priority_label: 'High' | 'Medium' | 'Low' | null
          total_funding_3y: number | null
          location_count: number | null
          participation_years: number | null
          enriched: boolean
          contact_name: string | null
          contact_title: string | null
          contact_email: string | null
          clinic_website: string | null
          linkedin_url: string | null
          enrichment_date: string | null
          processed: boolean
          assigned_to: string | null
          email_draft_created: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          hcp_number: string
          clinic_name: string
          address?: string | null
          city?: string | null
          state: string
          filing_date: string
          form_465_hash: string
          service_type?: string | null
          contract_length?: number | null
          bandwidth?: string | null
          priority_score?: number | null
          priority_label?: 'High' | 'Medium' | 'Low' | null
          total_funding_3y?: number | null
          location_count?: number | null
          participation_years?: number | null
          enriched?: boolean
          contact_name?: string | null
          contact_title?: string | null
          contact_email?: string | null
          clinic_website?: string | null
          linkedin_url?: string | null
          enrichment_date?: string | null
          processed?: boolean
          assigned_to?: string | null
          email_draft_created?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          hcp_number?: string
          clinic_name?: string
          address?: string | null
          city?: string | null
          state?: string
          filing_date?: string
          form_465_hash?: string
          service_type?: string | null
          contract_length?: number | null
          bandwidth?: string | null
          priority_score?: number | null
          priority_label?: 'High' | 'Medium' | 'Low' | null
          total_funding_3y?: number | null
          location_count?: number | null
          participation_years?: number | null
          enriched?: boolean
          contact_name?: string | null
          contact_title?: string | null
          contact_email?: string | null
          clinic_website?: string | null
          linkedin_url?: string | null
          enrichment_date?: string | null
          processed?: boolean
          assigned_to?: string | null
          email_draft_created?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      system_alerts: {
        Row: {
          id: string
          alert_type: 'usac_rule_update' | 'system_error' | 'workflow_notification'
          title: string
          message: string | null
          url: string | null
          severity: 'info' | 'warning' | 'error'
          read: boolean
          created_at: string
          expires_at: string | null
        }
        Insert: {
          id?: string
          alert_type: 'usac_rule_update' | 'system_error' | 'workflow_notification'
          title: string
          message?: string | null
          url?: string | null
          severity?: 'info' | 'warning' | 'error'
          read?: boolean
          created_at?: string
          expires_at?: string | null
        }
        Update: {
          id?: string
          alert_type?: 'usac_rule_update' | 'system_error' | 'workflow_notification'
          title?: string
          message?: string | null
          url?: string | null
          severity?: 'info' | 'warning' | 'error'
          read?: boolean
          created_at?: string
          expires_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
