#!/bin/bash

# Supabase credentials
PROJECT_REF="fhuqiicgmfpnmficopqp"
SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodXFpaWNnbWZwbm1maWNvcHFwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjQzOTkzNiwiZXhwIjoyMDc4MDE1OTM2fQ.mftyuE4grE-CSaT-KQh6iyzV1pcdBnwyarGAm6OFbf8"

echo "========================================="
echo "Supabase Schema Deployment Instructions"
echo "========================================="
echo ""
echo "To deploy the schema to Supabase, follow these steps:"
echo ""
echo "1. Open your browser and go to:"
echo "   https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"
echo ""
echo "2. Copy the ENTIRE contents of this file:"
echo "   $(pwd)/database/schema.sql"
echo ""
echo "3. Paste it into the SQL Editor in Supabase Dashboard"
echo ""
echo "4. Click 'Run' (or press Ctrl+Enter) to execute the schema"
echo ""
echo "5. You should see a success message indicating tables were created"
echo ""
echo "Note: Some statements may show warnings if objects already exist."
echo "This is normal and safe to ignore."
echo ""
echo "========================================="
echo ""
